no name: Post welcome comment
on:
  push:
    branches:
      - main
      
permissions:
  pull-requests: write
jobs:
  increment_minor:
    name: get version stored in file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            version.txt
          sparse-checkout-cone-mode: false
      - id: get_version
        run: |
          version=$(cat ./version.txt)
          version_array=(${version//./ } )
          ((version_array[1]++))
          ((version_array[2]=0))
          echo "${version_array[0]}.${version_array[1]}.${version_array[2]})" > ./version.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./version.txt
          git commit -m "bot-generated"
          git push
          git tag -a "${version_array[0]}.${version_array[1]}.${version_array[2]})" -m "Initial public release" master
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
