name: increment minor version on push commited

on:
  pull_request:
    types:
      - closed
      
permissions:
  pull-requests: write
jobs:
  increment_minor:
    if: github.event.pull_request.merged == true
    name: get version stored in file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            version.txt
          sparse-checkout-cone-mode: false
      - id: get_version
        run: |
          echo "getting version number"
          version=$(cat ./version.txt)
          echo "splitting version number"
          version_array=(${version//./ } )
          echo "incrementing version number"
          ((version_array[1]++))
          ((version_array[2]=0))
          echo saving version number"
          echo "${version_array[0]}.${version_array[1]}.${version_array[2]}" > ./version.txt
          echo "configuring git"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          echo "pusshing version file"
          git add ./version.txt
          git commit -m "bot-generated"
          git push
          echo "setting release"
          git tag -a "${version_array[0]}.${version_array[1]}.${version_array[2]}" -m "Initial public release" master
          git push --tags
          echo "end"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
